		<div id="AdminUseraccount" class="box box-normal box-solid" style="max-width: 600px;min-width: 330px;">
			<div class="overlay" style="display: none;">
				<i class="fa fa-refresh fa-spin"></i> 
			</div>
			<div class="box-header with-border">
				<h3 class="box-title">AdminUseraccount</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-click="box-search" >
						<i class="fa fa-search" data-toggle="tooltip" data-original-title="search"></i>					
					</button>
					<button class="btn btn-box-tool" data-click="box-refresh" >
						<i class="fa fa-refresh" data-toggle="tooltip" data-original-title="refresh"></i>					
					</button>
					<div class="btn-group" data-click="box-filed" data-table="AdminPurviewlist_List">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                       			<i class="fa fa-table" data-toggle="tooltip" data-original-title="欄位顯示"></i>	
                            </button>
                            <ul class="dropdown-menu" ></ul>
                    </div>					
					<button class="btn btn-box-tool" data-widget="collapse">					
						<i class="fa fa-minus"></i>
					</button>
					
				</div>
				
			</div>
			<!-- /.box-header -->
			
			<div class="box-body no-padding">
				<table class="table table-condensed" data-table="AdminPurviewlist_List">
					<thead>
						<tr>
							<th style="width: 10px">#</th>
							<th>帳號</th>							
							<th>姓名</th>
							<th>群組</th>
							<th>Purview</th>
						</tr>
					</thead>
					<tbody>
                    <?php if(isset($AdminUseraccount)):?>
					<?php foreach ($AdminUseraccount AS $list):?>
					<tr data-onshelf="<?php echo $list['onshelf_css'];?>">
							<td><?php echo $list['id'];?></td>	
							<td><?php echo $list['account'];?></td>	
							<td><?php echo $list['name'];?></td>
							<td><?php echo $list['AdminUsergroup'];?></td>
							
							<td>				
								<span>	
								<?php if(isset($list['purviewAction'])):?>
								<?php foreach ($list['purviewAction'] AS $action):?>
								<button class="btn btn-box-tool" data-click="item-<?php echo $action['code'];?>" data-id="<?php echo $list['id'];?>"  >
									<i class="fa <?php echo $action['icon'];?>" data-toggle="tooltip" title="" data-original-title="<?php echo $action['name'];?>"></i>
								</button>
								<?php endforeach;?>
								<?php endif;?>
							
								</span>
							</td>
						</tr>
					<?php endforeach;?>
					<?php endif;?>
                    
                  </tbody>
				  <tfoot>
						<tr>
							<td colspan="99">
								<div id="insertBox" class="direct-chat-primary" data-check="">							
									<div class="input-group" style="width: 100%">
									<?php if(isset($AdminUsergroup)):?>
									 <select id="AdminUsergroup" class="form-control" style="width: 10%;min-width: 100px;">
									<?php foreach ($AdminUsergroup AS $list):?>								
	                        			<option value="<?php echo $list['id'];?>"><?php echo $list['name'];?></option>  
									<?php endforeach;?>
									  </select>
									<?php endif;?>
									
									 <input id="insertAccount" class="form-control" style="width: auto;max-width: 440px;"
											placeholder="Type Account">							
										
									</div>
									<div class="direct-chat-msg right">
										<button class="btn btn-primary" data-click="item-insert">
												<i class="fa fa-plus"></i>
											</button>
		                          		<div class="direct-chat-text" data-message>
		                            		Type a name to create account
		                          		</div>
	                        		</div>
                        		</div>
							</td>
						</tr>
					</tfoot>
				</table>
			</div>
			
			<script>
			
			function boxview(eId,info){

				var el = $('#'+eId+'_Box');
				
				if(typeof(el) =='undefined') {
					console.info('no element');
					return false;
				}
				
				$(el).attr('data-refresh',"before").children('DIV.overlay').show();
				var url = 'boxview/'+eId;
				
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){					
					  $(el).before(data);  
					  $('[data-refresh="before"]').remove();			  
				  }
				});
			}
			
			$('#AdminUseraccount button[data-click="item-edit"]').on('click',function(){
				var info = {
						id:$(this).attr('data-id'),
						data:'AdminUseraccount',
						controller:"account",
					};
				boxview('purviewlist',info);
			});
			
			
			$('#AdminUseraccount button[data-click="item-onshelf"],#AdminUseraccount button[data-click="item-offshelf"]').on('click',function(){
				var this_el = $(this);
				
				var id =  $(this).attr('data-id');
				var url = 'account/'+this_el.attr('data-click').replace('item-','');	
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  id : id,
				  },
				  success: function(data){	
					  if(data == 'offshelf' || data == 'onshelf') this_el.parents('tr').attr('data-onshelf',data);
					  else console.info('error');
				  }
				});

			});
			$('#insertAccount').on('keyup',function(){
				
				var url = 'jsonview/accountcheck';
				var info = {
						account:$(this).val()
				};
				
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'json',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){	
						if(data){

							
							$('#insertBox').attr('class','direct-chat-'+data['css']).attr('data-check',data['check']);
							$('#insertBox DIV[data-message]').html(data['message']);
							$('#insertBox button[data-click="item-insert"]').attr('class','btn btn-'+data['css'])
						}
					  
				  }
				});
				
			})
			
			$('#AdminUseraccount button[data-click="item-insert"]').on('click',function(){

				
				if($('#insertBox').attr('data-check') < 1) return false;
				var account =  $('#insertAccount').val();
				var usergroup  = $('#AdminUsergroup').val();
				
				var pw = prompt("新增帳號"+account+" 密碼:", "");

				if(pw != prompt("新增帳號"+account+" 密碼確認:", "")){
					alert('密碼有誤!');
					return false;
				}
				
				
				
				var info = {
					  account:account,
					  usergroup:usergroup,
					  pw:pw
				  }
				 
				var url = 'account/insert/';
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){
					 console.info(data);
					 if(data = 'refresh') boxRefresh($('#AdminUseraccount'));;
				  }
				});
				
			})
			</script>
			
		</div>