		<div id="AdminPurviewlist_List" class="box box-normal box-solid" style="max-width: 600px;">
			<div class="overlay" style="display: none;">
				<i class="fa fa-refresh fa-spin"></i> 
			</div>
			<div class="box-header with-border">
				<h3 class="box-title">AdminPurviewlist List</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-click="box-search" >
						<i class="fa fa-search" data-toggle="tooltip" data-original-title="search"></i>					
					</button>
					<button class="btn btn-box-tool" data-click="box-refresh" >
						<i class="fa fa-refresh" data-toggle="tooltip" data-original-title="refresh"></i>					
					</button>
					<div class="btn-group" data-click="box-filed" data-table="AdminPurviewlist_List">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                       			<i class="fa fa-table" data-toggle="tooltip" data-original-title="欄位顯示"></i>	
                            </button>
                            <ul class="dropdown-menu" ></ul>
                    </div>					
					<button class="btn btn-box-tool" data-widget="collapse">					
						<i class="fa fa-minus"></i>
					</button>
					
				</div>
				
			</div>
			<!-- /.box-header -->
			
			<div class="box-body no-padding">
				<table class="table table-condensed" data-table="AdminPurviewlist_List">
					<thead>
						<tr>
							<th style="width: 10px">#</th>
							<th>後台功能</th>							
							<th>權限</th>
							<th>Type</th>
							<th>Purview</th>
						</tr>
					</thead>
					<tbody>
                    <?php if(isset($AdminPurviewlist)):?>
					<?php foreach ($AdminPurviewlist AS $list):?>
					<tr data-onshelf="<?php echo $list['onshelf_css'];?>">
							<td><?php echo $list['id'];?></td>	
							<td><?php echo $list['controllerName'];?></td>	
							<td><?php echo $list['purviewName'];?></td>
							<td>
								<input data-field="action_type" type="number" style="width:30px;" value="<?php echo $list['action_type'];?>" data-id="<?php echo $list['id'];?>"/>
							</td>
							<td>				
								<span>	
								<?php if(isset($list['purviewAction'])):?>
								<?php foreach ($list['purviewAction'] AS $action):?>
								<button class="btn btn-box-tool" data-click="item-<?php echo $action['code'];?>" data-id="<?php echo $list['id'];?>"  >
									<i class="fa <?php echo $action['icon'];?>" data-toggle="tooltip" title="" data-original-title="<?php echo $action['name'];?>"></i>
								</button>
								<?php endforeach;?>
								<?php endif;?>
							
								</span>
							</td>
						</tr>
					<?php endforeach;?>
					<?php endif;?>
                    
                  </tbody>
					<tfoot>
						<tr>
							<td colspan="99">
								<div class="input-group" style="width: 100%">
								<?php if(isset($AdminController)):?>
								 <select id="AdminController" class="form-control" style="width: 10%;min-width: 100px;">
								<?php foreach ($AdminController AS $list):?>								
                        			<option value="<?php echo $list['id'];?>"><?php echo $list['name'];?></option>  
								<?php endforeach;?>
								  </select>
								<?php endif;?>
								
								 <?php if(isset($AdminPurview)):?>
								 <select id="AdminPurview" class="form-control" style="width: 10%;min-width: 100px;">
								<?php foreach ($AdminPurview AS $list):?>								
                        			<option value="<?php echo $list['id'];?>"><?php echo $list['name'];?><i class="fa <?php echo $list['icon'];?>"></i></option>  
								<?php endforeach;?>
								  </select>
								<?php endif;?>								
									
									<div class="input-group-btn">
										<button class="btn btn-warning" data-click="item-insert">
											<i class="fa fa-plus"></i>
										</button>
									</div>
								</div>
								
							</td>
						</tr>
					</tfoot>
				</table>
			</div>
			
			<script>

			
			function setBoxFiled(name) {

				$('#'+name+' DIV[data-click="box-filed"] UL').html('');
				
				$('#'+name+' TABLE[data-table="'+name+'"] thead tr').find('TH').each(function(index){
					var title=$(this).attr("title");
					if(typeof(title) == "undefined") title=$(this).html();		
					
					var add_li = document.createElement('LI');
					add_li.innerHTML='<a>'+title+'</a>';
					
					
					if(typeof(title) != "undefined") {
						$('#'+name+' DIV[data-click="box-filed"] UL').append(add_li);
						if($(this).hasClass("rowhide")) $(add_li).addClass("rowhide");		
					}
					
				    if($('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hasClass("rowhide"))
						{
						$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hide();  
						$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').hide();
						}	
				});

				var items = $('#'+name+' DIV[data-click="box-filed"] UL li').click(function() {
				    var index = items.index(this);
				    
				    if($('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').is(':visible'))
					{ $(this).addClass("rowhide"); 
					$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hide(); 
					$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').hide();  }
					else 
					{ $(this).removeClass("rowhide"); 
					$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').show(); 
					$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').show(); } 
				});
			}
			
			function boxRefresh(el){
				if(typeof(el) =='undefined') {
					console.info('no element');
					return false;
				}
				
				$(el).attr('data-refresh',"before").children('DIV.overlay').show();
				var url = 'purview/views/viewContent';
				var info = false;
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){					
					  $(el).before(data);  
					  $('[data-refresh="before"]').remove();
					  setBoxFiled('AdminPurviewlist_List');					  
				  }
				});
			}
			$('DIV[data-click="box-filed"]').each(function(){
				setBoxFiled($(this).attr('data-table'));
			});
			
					
			$('#AdminPurviewlist_List button[data-click="box-refresh"]').on('click',function(){				
				boxRefresh($('#AdminPurviewlist_List'));
			});

			$('#AdminPurviewlist_List button[data-click="box-search"]').on('click',function(){				
				
				//if ( $('#box-search').is(":hidden") ) $('#box-search').show();
				//else $('#box-search').hide();

			});

			$('#AdminPurviewlist_List button[data-click="item-onshelf"],#AdminPurviewlist_List button[data-click="item-offshelf"]').on('click',function(){
				var this_el = $(this);
				
				var id =  $(this).attr('data-id');
				var url = 'purview/'+this_el.attr('data-click').replace('item-','');	
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  id : id,
				  },
				  success: function(data){	
					  if(data == 'offshelf' || data == 'onshelf') this_el.parents('tr').attr('data-onshelf',data);
					  else console.info('error');
				  }
				});

				
			});
			

			$('#AdminPurviewlist_List INPUT[data-field]').on('change',function(){		
					var id =  $(this).attr('data-id');
					var field = $(this).attr('data-field');
					var value = $(this).val();

					
					var url = 'purview/update/';
					$.ajax({
						url: url,
					  cache: false,
						dataType: 'html',
					  type: 'POST',
					  data:{
						  info:{
							  id:id,
							  value:value,
							  field:field,
						  }
					  },
					  success: function(data){
						 console.info(data);
						 if(data == 'refresh') boxRefresh($('#AdminPurviewlist_List'));
					  }
					});
					

				});
			
			$('#AdminPurviewlist_List button[data-click="item-delete"]').on('click',function(){				
				console.info($(this).attr('data-id'));
				var id =  $(this).attr('data-id');

				var url = 'purview/delete/';
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:{
						  id:id,
					  }
				  },
				  success: function(data){
					 console.info(data);
					 if(data == 'refresh') boxRefresh($('#AdminPurviewlist_List'));
				  }
				});
				
				
			});
			
			$('#AdminPurviewlist_List button[data-click="item-insert"]').on('click',function(){
				var ctrl_id =  $('#AdminController').val();
				var pur_id = $('#AdminPurview').val();
				
				var url = 'purview/insert/';
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:{
						  controller_id:ctrl_id,
						  purview_id:pur_id
					  }
				  },
				  success: function(data){
					 console.info(data);
					 if(data == 'refresh') boxRefresh($('#AdminPurviewlist_List'));;
				  }
				});
				
			})
			
			
			
			
			</script>
			
		</div>