<div id="UserGroupList" class="box box-normal box-solid">
			<div class="overlay" style="display: none;">
				<i class="fa fa-refresh fa-spin"></i> 
			</div>
			<div class="box-header with-border">
				<h3 class="box-title">UserGroup List</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-click="box-refresh" >
						<i class="fa fa-refresh" data-toggle="tooltip" data-original-title="refresh"></i>					
					</button>
					<button class="btn btn-box-tool" data-widget="collapse">
						<i class="fa fa-minus"></i>
					</button>

				</div>
				<!-- /.box-tools -->
			</div>
			<!-- /.box-header -->
			<div class="box-body no-padding">			
				<table class="table table-condensed">
					<thead>
						<tr>
							<th style="width: 10px">#</th>
							<th >Name</th>
							<th >Purview</th>
						</tr>
					</thead>
					<tbody>
                    <?php if(isset($Usergroup)):?>
					<?php foreach ($Usergroup AS $list):?>
					<tr data-onshelf="<?php echo $list['onshelf_css'];?>">
							<td><?php echo $list['id'];?></td>
							<td><?php echo $list['name'];?></td>
							<td>
								<span>	
								<?php if(isset($list['purviewAction'])):?>
								<?php foreach ($list['purviewAction'] AS $action):?>
								<button class="btn btn-box-tool" data-click="item-<?php echo $action['code'];?>" data-id="<?php echo $list['id'];?>"  >
									<i class="fa <?php echo $action['icon'];?>" data-toggle="tooltip" title="" data-original-title="<?php echo $action['name'];?>"></i>
								</button>
								<?php endforeach;?>
								<?php endif;?>
							
								</span>
								<button class="btn btn-box-tool" data-click="item-person" data-id="<?php echo $list['id'];?>">
									<i class="fa ion-person-add"></i>
								</button>
														
							</td>
						</tr>
					<?php endforeach;?>
					<?php endif;?>
                    
                  </tbody>
					<tfoot>
						<tr>
							<td colspan="99">
								<div class="input-group" style="width: 100%">
									<input class="form-control" placeholder="Type UserGroup Name ...">
									<div class="input-group-btn">
										<button class="btn btn-warning">
											<i class="fa fa-plus"></i>
										</button>
									</div>
								</div>
							</td>
						</tr>
					</tfoot>
				</table>
			</div>
			<script>
function setBoxFiled(name) {

	$('#'+name+' DIV[data-click="box-filed"] UL').html('');
	
	$('#'+name+' TABLE[data-table="'+name+'"] thead tr').find('TH').each(function(index){
		var title=$(this).attr("title");
		if(typeof(title) == "undefined") title=$(this).html();		
		
		var add_li = document.createElement('LI');
		add_li.innerHTML='<a>'+title+'</a>';
		
		
		if(typeof(title) != "undefined") {
			$('#'+name+' DIV[data-click="box-filed"] UL').append(add_li);
			if($(this).hasClass("rowhide")) $(add_li).addClass("rowhide");		
		}
		
	    if($('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hasClass("rowhide"))
			{
			$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hide();  
			$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').hide();
			}	
	});

	var items = $('#'+name+' DIV[data-click="box-filed"] UL li').click(function() {
	    var index = items.index(this);
	    
	    if($('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').is(':visible'))
		{ $(this).addClass("rowhide"); 
		$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hide(); 
		$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').hide();  }
		else 
		{ $(this).removeClass("rowhide"); 
		$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').show(); 
		$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').show(); } 
	});
}
			
function boxview(eId,info){

	var el = $('#'+eId+'_Box');
	
	if(typeof(el) =='undefined') {
		console.info('no element');
		return false;
	}
	
	$(el).attr('data-refresh',"before").children('DIV.overlay').show();
	var url = 'boxview/'+eId;
	
	$.ajax({
		url: url,
	  cache: false,
		dataType: 'html',
	  type: 'POST',
	  data:{
		  info:info
	  },
	  success: function(data){					
		  $(el).before(data);  
		  $('[data-refresh="before"]').remove();			  
	  }
	});
}

function boxRefresh(el){
	if(typeof(el) =='undefined') {
		console.info('no element');
		return false;
	}
	
	$(el).attr('data-refresh',"before").children('DIV.overlay').show();
	var url = 'usergroup/list/viewContent';
	var info = false;
	$.ajax({
		url: url,
	  cache: false,
		dataType: 'html',
	  type: 'POST',
	  data:{
		  info:info
	  },
	  success: function(data){					
		  $(el).before(data);  
		  $('[data-refresh="before"]').remove();
		  setBoxFiled('UserGroupList');					  
	  }
	});
}

		
$('#UserGroupList button[data-click="box-refresh"]').on('click',function(){				
	boxRefresh($('#UserGroupList'));
});
		
$('#UserGroupList button[data-click="item-edit"]').on('click',function(){
	var info = {
			id:$(this).attr('data-id'),
			data:'AdminUsergroup',
			controller:"usergroup",
		};
	boxview('purviewlist',info);
});


$('#UserGroupList button[data-click="item-person"]').on('click',function(){
	var info = {
			id:$(this).attr('data-id'),
			data:'AdminUsergroup'
		};
	boxview('account',info);
});

</script>
		</div>