		<div id="Article" class="box box-normal box-solid" style="max-width: 600px;min-width: 330px;">
			<div class="overlay" style="display: none;">
				<i class="fa fa-refresh fa-spin"></i> 
			</div>
			<div class="box-header with-border">
				<h3 class="box-title">Article</h3>
				<div class="box-tools pull-right">
					<button class="btn btn-box-tool" data-click="box-search" >
						<i class="fa fa-search" data-toggle="tooltip" data-original-title="search"></i>					
					</button>
					<button class="btn btn-box-tool" data-click="box-refresh" >
						<i class="fa fa-refresh" data-toggle="tooltip" data-original-title="refresh"></i>					
					</button>
					<div class="btn-group" data-click="box-filed" data-table="AdminPurviewlist_List">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                       			<i class="fa fa-table" data-toggle="tooltip" data-original-title="欄位顯示"></i>	
                            </button>
                            <ul class="dropdown-menu" ></ul>
                    </div>					
					<button class="btn btn-box-tool" data-widget="collapse">					
						<i class="fa fa-minus"></i>
					</button>
					
				</div>
				
			</div>
			<!-- /.box-header -->
			
			<div class="box-body no-padding">
				<table class="table table-condensed" data-table="AdminPurviewlist_List">
					<thead>
						<tr>
							<th style="width: 10px">#</th>												
							<th>標題</th>
							<th>群組</th>
							<th>Purview</th>
						</tr>
					</thead>
					<tbody>
                    <?php if(isset($Article)):?>
					<?php foreach ($Article AS $list):?>
					<tr data-onshelf="<?php echo $list['onshelf_css'];?>">
							<td><?php echo $list['id'];?></td>
							<td><?php echo $list['title'];?></td>
							<td><?php echo $list['ProductCategory'];?></td>
							
							<td>				
								<span>	
								<?php if(isset($list['purviewAction'])):?>
								<?php foreach ($list['purviewAction'] AS $action):?>
								<button class="btn btn-box-tool" data-click="item-<?php echo $action['code'];?>" data-id="<?php echo $list['id'];?>"  >
									<i class="fa <?php echo $action['icon'];?>" data-toggle="tooltip" title="" data-original-title="<?php echo $action['name'];?>"></i>
								</button>
								<?php endforeach;?>
								<?php endif;?>
							
								</span>
							</td>
						</tr>
					<?php endforeach;?>
					<?php endif;?>
                    
                  </tbody>
				  <tfoot>
						<tr>
							<td colspan="99">
								
							</td>
						</tr>
					</tfoot>
				</table>
			</div>
			
			<script>
			
			
			
			$('#Article button[data-click="item-edit"]').on('click',function(){

				$('#Article button[data-click="item-edit"]').removeClass('bg-light-blue');
				$(this).addClass('bg-light-blue');
				var id = $(this).attr('data-id');
				var url = 'jsonview/articlecheck';
				var info = {
						id: id,
					};
				
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'json',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){	
					  $('#Preview').attr('data-id',id);
					  
					 					  
					  for(var k in data['preview']){
						$('#Preview [preview="'+k+'"]').html(data['preview'][k]);
					  }
					  
				  }
				});
				
			});
			function boxview(eId,info){

				var el = $('#'+eId+'_Box');
				
				if(typeof(el) =='undefined') {
					console.info('no element');
					return false;
				}
				
				$(el).attr('data-refresh',"before").children('DIV.overlay').show();
				var url = 'boxview/'+eId;
				
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){					
					  $(el).before(data);  
					  $('[data-refresh="before"]').remove();			  
				  }
				});
			}
			
			
			
			
			$('#Article button[data-click="item-onshelf"],#Article button[data-click="item-offshelf"]').on('click',function(){
				var this_el = $(this);
				
				var id =  $(this).attr('data-id');
				var url = 'article/'+this_el.attr('data-click').replace('item-','');	
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  id : id,
				  },
				  success: function(data){	
					  if(data == 'offshelf' || data == 'onshelf') this_el.parents('tr').attr('data-onshelf',data);
					  else console.info('error');
				  }
				});

			});
			
			
			
			$('#Article button[data-click="item-insert"]').on('click',function(){

				
				if($('#insertBox').attr('data-check') < 1) return false;
				var video_id =  $('#insertArticle').val();
				var category_id  = $('#ProductCategory').val();
				
				var post = {}; 
					$('#Preview [preview]').each(function(){						
						post[$(this).attr("preview")] = $(this).html();
					});				
				
				
				var info = {
					  video_id : video_id,
					  category_id : category_id,
					  post : post
				  }
				 
				var url = 'article/insert/';
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){
					 console.info(data);
					 $('#preview_html').html('');
					 $('#Preview [preview]').html('');
					 
					 if(data = 'refresh') boxRefresh($('#Article'));;
				  }
				});
				
			});

			function setBoxFiled(name) {

				$('#'+name+' DIV[data-click="box-filed"] UL').html('');
				
				$('#'+name+' TABLE[data-table="'+name+'"] thead tr').find('TH').each(function(index){
					var title=$(this).attr("title");
					if(typeof(title) == "undefined") title=$(this).html();		
					
					var add_li = document.createElement('LI');
					add_li.innerHTML='<a>'+title+'</a>';
					
					
					if(typeof(title) != "undefined") {
						$('#'+name+' DIV[data-click="box-filed"] UL').append(add_li);
						if($(this).hasClass("rowhide")) $(add_li).addClass("rowhide");		
					}
					
				    if($('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hasClass("rowhide"))
						{
						$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hide();  
						$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').hide();
						}	
				});

				var items = $('#'+name+' DIV[data-click="box-filed"] UL li').click(function() {
				    var index = items.index(this);
				    
				    if($('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').is(':visible'))
					{ $(this).addClass("rowhide"); 
					$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').hide(); 
					$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').hide();  }
					else 
					{ $(this).removeClass("rowhide"); 
					$('#'+name+' TABLE[data-table="'+name+'"] thead th:nth-child('+(index+1)+')').show(); 
					$('#'+name+' TABLE[data-table="'+name+'"] tbody td:nth-child('+(index+1)+')').show(); } 
				});
			}
			function boxRefresh(el){
				if(typeof(el) =='undefined') {
					console.info('no element');
					return false;
				}
				
				$(el).attr('data-refresh',"before").children('DIV.overlay').show();
				var url = 'article/views/viewContent';
				var info = false;
				$.ajax({
					url: url,
				  cache: false,
					dataType: 'html',
				  type: 'POST',
				  data:{
					  info:info
				  },
				  success: function(data){					
					  $(el).before(data);  
					  $('[data-refresh="before"]').remove();
					  setBoxFiled('Article');					  
				  }
				});
			}
			
			
			</script>
			
		</div>